import { useState } from 'react'
import { analyzeReport } from '../../services/api'

export default function ReportTab({ insights, jobId }) {
  const [model,     setModel]     = useState('groq')
  const [focus,     setFocus]     = useState('general')
  const [report,    setReport]    = useState(insights?.llm_report || '')
  const [modelUsed, setModelUsed] = useState(insights?.model_used || '')
  const [loading,   setLoading]   = useState(false)
  const [error,     setError]     = useState(null)

  const regenerate = async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await analyzeReport(
        {
          summary:           insights?.summary,
          segments:          insights?.cluster_profiles,
          association_rules: insights?.association_rules,
          trend_data:        insights?.trend_data,
          silhouette_score:  insights?.silhouette_score,
        },
        model,
        focus
      )
      setReport(res.data.report)
      setModelUsed(res.data.model_used)
    } catch (e) {
      setError('Failed to generate report. Check your API key settings.')
    } finally {
      setLoading(false)
    }
  }

  const renderReport = (text) => {
    if (!text?.trim()) return (
      <div style={S.emptyReport}>
        <div style={S.emptyIcon}>✦</div>
        <div style={S.emptyMsg}>No report generated yet. Click "Regenerate report" to create one.</div>
      </div>
    )

    return (text || '').split('\n').map((line, i) => {
      if (line.startsWith('## '))
        return <h2 key={i} style={S.h2}>{line.replace(/^##\s*/, '')}</h2>
      if (line.startsWith('### '))
        return <h3 key={i} style={S.h3}>{line.replace(/^###\s*/, '')}</h3>
      if (line.match(/^[\-\*] /))
        return <div key={i} style={S.li}>{line.replace(/^[\-\*] /, '').replace(/\*\*(.*?)\*\*/g, '$1')}</div>
      if (line.match(/^\d+\. /))
        return <div key={i} style={S.li}>{line.replace(/\*\*(.*?)\*\*/g, '$1')}</div>
      if (line.trim() === '')
        return <div key={i} style={{ height: 12 }} />
      return <p key={i} style={S.p}>{line.replace(/\*\*(.*?)\*\*/g, '$1')}</p>
    })
  }

  return (
    <div>
      <div style={S.controls}>
        <div style={S.controlGroup}>
          <label style={S.label}>AI Model</label>
          <select value={model} onChange={e => setModel(e.target.value)} style={S.select}>
            <option value="groq">Groq — Llama 3.3 70B (free)</option>
            <option value="gemini">Google Gemini 2.0</option>
            <option value="openai">OpenAI GPT-4o Mini</option>
            <option value="anthropic">Anthropic Claude</option>
          </select>
        </div>
        <div style={S.controlGroup}>
          <label style={S.label}>Strategic focus</label>
          <select value={focus} onChange={e => setFocus(e.target.value)} style={S.select}>
            <option value="general">General overview</option>
            <option value="retention">Customer retention</option>
            <option value="upsell">Upsell & cross-sell</option>
            <option value="acquisition">New acquisition</option>
            <option value="seasonal">Seasonal trends</option>
          </select>
        </div>
        <div style={S.controlGroup}>
          <label style={S.label}>&nbsp;</label>
          <button onClick={regenerate} disabled={loading} style={{
            ...S.regenBtn,
            opacity: loading ? 0.6 : 1,
            cursor:  loading ? 'not-allowed' : 'pointer',
          }}>
            {loading ? 'Generating...' : 'Regenerate report ↗'}
          </button>
        </div>
      </div>

      {error && <div style={S.error}>{error}</div>}

      <div style={S.section}>
        {modelUsed && (
          <div style={S.reportMeta}>
            Generated by <span style={S.badge}>{modelUsed}</span>
          </div>
        )}
        <div style={S.report}>
          {renderReport(report)}
        </div>
      </div>
    </div>
  )
}

const S = {
  controls:     { display: 'flex', alignItems: 'flex-end', gap: 12, marginBottom: '1.5rem', flexWrap: 'wrap' },
  controlGroup: { display: 'flex', flexDirection: 'column', gap: 4 },
  label:        { fontSize: 12, color: '#888780' },
  select:       { fontSize: 13, padding: '6px 10px', borderRadius: 8, border: '0.5px solid #D3D1C7', background: 'white', color: '#1a1a1a' },
  regenBtn:     { padding: '7px 16px', background: '#EEEDFE', color: '#534AB7', border: '0.5px solid #AFA9EC', borderRadius: 8, fontSize: 13, fontWeight: 500 },
  error:        { fontSize: 13, color: '#993C1D', background: '#FAECE7', padding: '10px 14px', borderRadius: 8, marginBottom: 12 },
  section:      { background: 'white', border: '0.5px solid #E8E6DF', borderRadius: 12, padding: '2rem' },
  reportMeta:   { fontSize: 12, color: '#888780', marginBottom: '1.5rem' },
  badge:        { background: '#EEEDFE', color: '#534AB7', padding: '2px 8px', borderRadius: 999, fontSize: 11, fontWeight: 500, marginLeft: 4 },
  report:       { lineHeight: 1.8 },
  h2:           { fontSize: 20, fontFamily: "'Instrument Serif', serif", color: '#1a1a1a', marginTop: 24, marginBottom: 8 },
  h3:           { fontSize: 16, fontFamily: "'Instrument Serif', serif", color: '#1a1a1a', marginTop: 16, marginBottom: 6 },
  li:           { fontSize: 14, color: '#5F5E5A', paddingLeft: 16, marginBottom: 6, borderLeft: '2px solid #AFA9EC' },
  p:            { fontSize: 14, color: '#5F5E5A', marginBottom: 6 },
  emptyReport:  { display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '48px 20px', gap: 12 },
  emptyIcon:    { fontSize: 32, color: '#D3D1C7' },
  emptyMsg:     { fontSize: 13, color: '#B4B2A9', textAlign: 'center' },
}