import { useState } from 'react'
import { analyzeReport } from '../../services/api'

export default function ReportTab({ insights, jobId }) {
  const [model,     setModel]     = useState('groq')
  const [focus,     setFocus]     = useState('general')
  const [report,    setReport]    = useState(insights.llm_report || '')
  const [modelUsed, setModelUsed] = useState(insights.model_used || '')
  const [loading,   setLoading]   = useState(false)
  const [error,     setError]     = useState(null)

  const regenerate = async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await analyzeReport(
        {
          summary:           insights.summary,
          segments:          insights.cluster_profiles,
          association_rules: insights.association_rules,
          forecasts:         {},
        },
        model,
        focus
      )
      setReport(res.data.report)
      setModelUsed(res.data.model_used)
    } catch (e) {
      setError('Failed to generate report. Check your API key.')
    } finally {
      setLoading(false)
    }
  }

  const lines = report.split('\n')

  return (
    <div>
      <div style={styles.controls}>
        <div style={styles.controlGroup}>
          <label style={styles.label}>Model</label>
          <select value={model} onChange={e => setModel(e.target.value)} style={styles.select}>
            <option value="groq">Groq — Llama 3.3 70B (free)</option>
            <option value="gemini">Gemini 2.0 Flash</option>
            <option value="openai">GPT-4o Mini</option>
            <option value="anthropic">Claude Sonnet</option>
          </select>
        </div>
        <div style={styles.controlGroup}>
          <label style={styles.label}>Focus</label>
          <select value={focus} onChange={e => setFocus(e.target.value)} style={styles.select}>
            <option value="general">General</option>
            <option value="retention">Retention</option>
            <option value="upsell">Upsell</option>
            <option value="acquisition">Acquisition</option>
            <option value="seasonal">Seasonal</option>
          </select>
        </div>
        <button onClick={regenerate} disabled={loading} style={styles.btn}>
          {loading ? 'Generating...' : 'Regenerate report ↗'}
        </button>
      </div>

      {error && <div style={styles.error}>{error}</div>}

      <div style={styles.section}>
        <div style={styles.reportMeta}>
          Generated by <span style={styles.modelBadge}>{modelUsed}</span>
        </div>
        <div style={styles.report}>
          {lines.map((line, i) => {
            if (line.startsWith('## ')) return (
              <div key={i} style={styles.h2}>{line.replace('## ', '')}</div>
            )
            if (line.startsWith('### ')) return (
              <div key={i} style={styles.h3}>{line.replace('### ', '')}</div>
            )
            if (line.startsWith('- ') || line.match(/^\d+\./)) return (
              <div key={i} style={styles.listItem}>
                {line.replace(/^- /, '').replace(/^\d+\. /, '').replace(/\*\*(.*?)\*\*/g, '$1')}
              </div>
            )
            if (line.trim() === '') return <div key={i} style={{height:8}} />
            return (
              <div key={i} style={styles.para}>
                {line.replace(/\*\*(.*?)\*\*/g, '$1')}
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}

const styles = {
  controls:     { display:'flex', alignItems:'flex-end', gap:12, marginBottom:'1.5rem', flexWrap:'wrap' },
  controlGroup: { display:'flex', flexDirection:'column', gap:4 },
  label:        { fontSize:12, color:'var(--color-text-secondary)' },
  select:       { minWidth:200 },
  btn:          { padding:'7px 16px', background:'#EEEDFE', color:'#534AB7', border:'0.5px solid #AFA9EC', borderRadius:'var(--border-radius-md)', fontSize:13, fontWeight:500, cursor:'pointer', alignSelf:'flex-end' },
  error:        { color:'var(--color-text-danger)', fontSize:13, marginBottom:'1rem' },
  section:      { background:'var(--color-background-primary)', border:'0.5px solid var(--color-border-tertiary)', borderRadius:'var(--border-radius-lg)', padding:'1.5rem' },
  reportMeta:   { fontSize:12, color:'var(--color-text-tertiary)', marginBottom:'1.5rem' },
  modelBadge:   { background:'#EEEDFE', color:'#534AB7', padding:'2px 8px', borderRadius:999, fontSize:11, fontWeight:500, marginLeft:4 },
  report:       { lineHeight:1.7 },
  h2:           { fontSize:17, fontWeight:500, color:'var(--color-text-primary)', marginTop:24, marginBottom:8 },
  h3:           { fontSize:15, fontWeight:500, color:'var(--color-text-primary)', marginTop:16, marginBottom:6 },
  listItem:     { fontSize:14, color:'var(--color-text-secondary)', paddingLeft:16, marginBottom:6, borderLeft:'2px solid #AFA9EC' },
  para:         { fontSize:14, color:'var(--color-text-secondary)', marginBottom:6 },
}