import { useState, useEffect } from 'react'
import { useParams } from 'react-router-dom'
import { getInsights } from '../services/api'
import {
  PieChart, Pie, Cell, Tooltip, Legend,
  BarChart, Bar, XAxis, YAxis, CartesianGrid, ResponsiveContainer
} from 'recharts'

const COLORS = ['#7F77DD', '#1D9E75', '#D85A30', '#BA7517', '#185FA5']

export default function DashboardPage() {
  const { jobId }         = useParams()
  const [insights, setInsights] = useState(null)
  const [loading, setLoading]   = useState(true)
  const [error, setError]       = useState(null)

  useEffect(() => {
    const fetchInsights = async () => {
      try {
        const response = await getInsights(jobId)
        setInsights(response.data)
      } catch (err) {
        setError('Could not load insights.')
      } finally {
        setLoading(false)
      }
    }
    fetchInsights()
  }, [jobId])

  if (loading) return <div style={styles.center}>Loading insights...</div>
  if (error)   return <div style={styles.center}>{error}</div>
  if (!insights) return null

  // Format segments for pie chart
  const segmentData = (insights.cluster_profiles || []).map(p => ({
    name:  p.label,
    value: p.size,
  }))

  // Format top rules for bar chart
  const rulesData = (insights.association_rules || [])
    .slice(0, 8)
    .map(r => ({
      rule:       `${r.antecedents.join('+')} → ${r.consequents.join('+')}`,
      lift:       r.lift,
      confidence: Math.round(r.confidence * 100),
    }))

  return (
    <div style={styles.container}>
      <h1 style={styles.title}>Customer Insights</h1>
      <p style={styles.subtitle}>
        {insights.summary?.total_customers} customers ·{' '}
        {insights.summary?.total_transactions} transactions ·{' '}
        ${insights.summary?.total_revenue?.toLocaleString()} revenue
      </p>

      {/* Summary cards */}
      <div style={styles.cardRow}>
        <div style={styles.card}>
          <p style={styles.cardLabel}>Customers</p>
          <p style={styles.cardValue}>{insights.summary?.total_customers}</p>
        </div>
        <div style={styles.card}>
          <p style={styles.cardLabel}>Avg Order Value</p>
          <p style={styles.cardValue}>${insights.summary?.avg_order_value}</p>
        </div>
        <div style={styles.card}>
          <p style={styles.cardLabel}>Segments Found</p>
          <p style={styles.cardValue}>{insights.n_clusters}</p>
        </div>
        <div style={styles.card}>
          <p style={styles.cardLabel}>Rules Found</p>
          <p style={styles.cardValue}>{insights.association_rules?.length}</p>
        </div>
      </div>

      {/* Segments pie chart */}
      <div style={styles.section}>
        <h2 style={styles.sectionTitle}>Customer Segments</h2>
        <ResponsiveContainer width="100%" height={300}>
          <PieChart>
            <Pie
              data={segmentData}
              cx="50%"
              cy="50%"
              outerRadius={100}
              dataKey="value"
              label={({ name, percent }) =>
                `${name} ${(percent * 100).toFixed(0)}%`
              }
            >
              {segmentData.map((_, index) => (
                <Cell key={index} fill={COLORS[index % COLORS.length]} />
              ))}
            </Pie>
            <Tooltip />
            <Legend />
          </PieChart>
        </ResponsiveContainer>
      </div>

      {/* Association rules bar chart */}
      <div style={styles.section}>
        <h2 style={styles.sectionTitle}>Top Purchase Patterns (Lift Score)</h2>
        <ResponsiveContainer width="100%" height={300}>
          <BarChart data={rulesData} layout="vertical"
            margin={{ left: 160, right: 20, top: 5, bottom: 5 }}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis type="number" />
            <YAxis type="category" dataKey="rule" width={150}
              tick={{ fontSize: 11 }} />
            <Tooltip />
            <Bar dataKey="lift" fill="#7F77DD" name="Lift Score" />
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* LLM Report */}
      <div style={styles.section}>
        <h2 style={styles.sectionTitle}>AI Strategy Report</h2>
        <p style={styles.modelBadge}>Generated by {insights.model_used}</p>
        <div style={styles.reportBox}>
          {insights.llm_report?.split('\n').map((line, i) => (
            <p key={i} style={{
              ...styles.reportLine,
              fontWeight: line.startsWith('##') ? '600' : '400',
              fontSize:   line.startsWith('##') ? '17px' : '15px',
              marginTop:  line.startsWith('##') ? '20px' : '4px',
            }}>
              {line.replace(/^##\s*/, '').replace(/\*\*/g, '')}
            </p>
          ))}
        </div>
      </div>
    </div>
  )
}

const styles = {
  container: {
    maxWidth: '900px',
    margin: '0 auto',
    padding: '40px 24px',
    fontFamily: 'system-ui, sans-serif',
  },
  center: {
    textAlign: 'center',
    padding: '80px',
    color: '#666',
    fontFamily: 'system-ui, sans-serif',
  },
  title: { fontSize: '28px', fontWeight: '600', color: '#1a1a1a', marginBottom: '8px' },
  subtitle: { fontSize: '15px', color: '#666', marginBottom: '32px' },
  cardRow: { display: 'flex', gap: '16px', marginBottom: '32px', flexWrap: 'wrap' },
  card: {
    flex: '1',
    minWidth: '140px',
    background: '#f4f4f4',
    borderRadius: '10px',
    padding: '16px',
  },
  cardLabel: { fontSize: '13px', color: '#666', margin: '0 0 6px' },
  cardValue: { fontSize: '24px', fontWeight: '600', color: '#1a1a1a', margin: 0 },
  section: { marginBottom: '40px' },
  sectionTitle: { fontSize: '18px', fontWeight: '500', marginBottom: '16px', color: '#1a1a1a' },
  modelBadge: { fontSize: '13px', color: '#7F77DD', marginBottom: '12px' },
  reportBox: {
    background: '#f9f9f9',
    borderRadius: '10px',
    padding: '24px',
    lineHeight: '1.7',
  },
  reportLine: { margin: '2px 0', color: '#333' },
}